### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by qrilka** [jaredly/django-appsettings#1]
I tried to use this app but instructions are not extensive enough and it looks like they are about some previous version (e.g. I don't see register method in app.py)

**Comment by jaredly** [comment]
Oh, sorry about that. The second example was correct... anyway I fixed the example. If you look in appsettings/**init**.py, you'll find the register function. So you can do
import appsettings
register = appsettings.register("mymodule")

**Comment by qrilka** [comment]
I have figured out the details about "register" yesterday but I could not get admin interface (through appsettings.urls) working - it fails saying something about 'var' and '**dict**'. Maybe adding some very sketchy app (just a a couple of files) could help here?
