### ISSUE TITLE
Any hints on settng up admin interface?

### ISSUE THREAD

**Issue by qrilka** [jaredly/django-appsettings#2]
I could not get admin interface (through appsettings.urls) working - it fails saying:

'NoneType' object has no attribute '_register'
django-appsettings/appsettings/__init__.py in meta, line 23

Maybe adding some very sketchy app (just a a couple of files) could help here?

**Comment by qrilka** [comment]
Looks like reading through the source code I have found the right combination:
I shout import app and use app.settings.mymodule. And that invokes autodiscovery.

You write "in the same way contrib.admin loads your admin.py" but for that to work you need to invoke "manually" admin.autodiscover(). So that's not very intuitive.

And also you use {% extends base_template %} and that doesn't looks like settings in my project.

Hope I'll start using those settings tomorrow.

And thanks for your app.

**Comment by qrilka** [comment]
with base_template I mean index.html and it does looks that it should be used for setings. I'd rather prefer something from contrib.admin. So it looks like I need to call appsettings views manually as base_template could not be set when using appsettings.urls

**Comment by qrilka** [comment]
Actually it looks like using customized views would do the trick so I stay with appsettings.urls

But I still think that some small example app could help in making appsettings more easy  to understand (at least at setting all the things up)

**Comment by jaredly** [comment]
I just committed up a fix for that, sorry; the admin interface should be working again. I'll try to get an example app together (and project) tomorrow.

**Comment by jaredly** [comment]
I made the template inheritance configurable, but set to "index.html" by default (in appsettings.urls)
