### ISSUE TITLE
Can not run syncdb with models referencing settings

### ISSUE THREAD

**Issue by qrilka** [jaredly/django-appsettings#4]
I get
psycopg2.ProgrammingError: relation "appsettings_setting" does not exist
when I try to run manage.py syncdb and my models in models.py reference settings from appsettings.

So I needed to comment out line settings=app.settings.my_app run syncdb and  change back the commented out line. It works fine for a test server but for production server it seems te be quite bad.

Also I have some other issue coming from using settings in class declaration but it is tied to django CMS so I'm not sure yet how could I reproduce it in some standalone app.

**Comment by qrilka** [comment]
Sorry, I commented 2 lines starting with "from appsettings import app" as db query comes with autodiscover() from app.py.

**Comment by jaredly** [comment]
Hmm that's an interesting problem. Appsettings is set up so that it can function fine without a database at all; currently it checks for a database, and if one exists, it assumes it has been installed (tables and all).

**Comment by qrilka** [comment]
But existing database != existing tables...

**Comment by jaredly** [comment]
quite right; so I could add a check for the table (and maybe complain to stderr if I don't find it), and hopefully fix your problem

**Comment by qrilka** [comment]
stderr seems to be quite reasonable

**Comment by jaredly** [comment]
Alright that should be fixed by the latest commit!
