### ISSUE TITLE
Possibly github issue

### ISSUE THREAD

**Issue by qrilka** [jaredly/django-appsettings#5]
Jared I see commit cb297e3 from my fork queue but can not apply it to my repository and it is not seen on http://github.com/jabapyth/django-appsettings/commits/master and in http://github.com/jabapyth/django-appsettings/blob/master/appsettings/models.py I don't see changes.

**Comment by jaredly** [comment]
Wow that's so weird -- git doesn't like it if you begin a commit message with "#". It's fixed now. (the important change was in settingsobj.py)

**Comment by qrilka** [comment]
Could not merge with github's "Fork Queue" so done it through command line git.
