### ISSUE TITLE
Changing settings from the UI does not affect (other) process / threads.

### ISSUE THREAD

**Issue by incuna** [jaredly/django-appsettings#6]
This app looks really useful but it seems that if a user changes a setting (using the UI) then this change is only reflected in the users process / thread. In a production environment the other processes / threads will not have their settings changed (until the server is restarted).

It would be possible to work around this by using a cache to store the settings.

This seems like a fundamental issue so maybe I missed something.

Thanks,

Max.

**Comment by jaredly** [comment]
That is not the case. Initial (default) settings are written in code, but all future modifications (made via the UI or programmatically) are stored in the database, which is universally accessible. The setup appsettings created makes it _appear_ as though you are merely changing a variable that is local to your process, but the change is actually committed to the database.

**Comment by incuna** [comment]
I saw that the defaults were written to the database but I could not see anything that would trigger other threads to read settings from the database (other than at startup).

Suppose that there are two threads, both will start with the same settings, initialised either  from the app or database. If you change a setting in one process it writes to the database and updates it's settings but the other thread does not get updated. (As far as I could tell it only reads from the database when first initialised). 

You could simulate this easily with two (django) shells to represent the (cgi,wsgi,gunicorn,..) threads that run on a production server. The django runserver has a single thread so you could also simulate with two runservers (on different ports).

You could modify settingsobj.Group.**getattr** to check the database but this would be expensive. My suggestion would be to use a cache backend (that is global to all threads) to cache the value then settingsobj.Group.**getattr** could use this. If no cache backend is set it could either fall back to the database or work as it currently does but I think this will be inconsistent on a (multi)threaded production server.

**Comment by jaredly** [comment]
Oh, you're right! Hadn't thought of that.
That seems like a great solution -- do you feel up to implementing it? You could [fork my repo](http://help.github.com/forking/), and then make a [pull request](http://github.com/guides/pull-requests), and I'd be really appreciate it :)
Or I'll work on it when I get the time (might be sometime next week).

Thanks for the solution

**Comment by incuna** [comment]
No problem, we have been looking for a good solution to the app / user settings issue for a little while.
We will try and look at it this week.

**Comment by jaredly** [comment]
I've pulled in the changes.
