### ISSUE TITLE
Python 2.6 syntax

### ISSUE THREAD

**Issue by timc3** [jaredly/django-appsettings#7]
You should not that the following:

```
@register
 class Story:
```

is not syntax that will work in Python 2.5, is there an alternative that you suggest for for that version? Like:

```
 class Story:
     # blah

 Story = register(Story)
```

If not you should make it known that this is for Python 2.6 onwards only.

**Comment by jaredly** [comment]
That alternative will work fine -- as far as I know, any

```
@decorator
def foo:pass
```

can be replaced with

```
def foo:pass
foo = decorator(foo)
```

the same works with classes.

**Comment by timc3** [comment]
Yes it does work fine, thought it would be helpful to others to have it posted here.

Thanks!

**Comment by jaredly** [comment]
Committed: 2b19d51ed76d9723b60c7f945e8f8fbe15c8a109
