### ISSUE TITLE
{% csrf_token %} missing in forms

### ISSUE THREAD

**Issue by mrcwd** [jaredly/django-appsettings#8]
{% csrf_token %} is needed in forms in django 1.2.  I could put this in my fork and push it to you if you like, but I'm not sure how it will affect older versions. 
What do you think?

**Comment by jaredly** [comment]
[committed](http://github.com/jabapyth/django-appsettings/commit/aab40b77bf7dba444871a56cba075374fab1c55b) =)
Thanks for the heads up.

**Comment by mrcwd** [comment]
welcome :)
