### ISSUE TITLE
can't see settings in admin

### ISSUE THREAD

**Issue by benbro** [jaredly/django-appsettings#9]
Hi

I can't see the settings I created in a settings.py filein the database.
Are they suppose to be created automatically when starting the server?
I couldn't see a management command to scan apps and create non-existing settings in the db.
Do I need to create settings both in a settings.py file and in the db in admin?
In addition, appsettings/ shows nothing

This is what I'm doing:
1. added the app to my app folder myproject/apps/appsettings
2. copied the template folder to my template folder
3. created a settings.py file under myproject/apps/myapp/settings.py
4. copied the code from the readme.
5. add appsettings to the main url.
6. added appsettings to my installed apps.

Thanks

**Comment by steinerkelvin** [comment]
Not working for me too. I modify the settings values, but they don't appear in the admin.

**Comment by Allan-Nava** [comment]
Is still alive the project?

**Comment by aasmpro** [comment]
@benbro @quleuber @Allan-Nava take a look at [django-zero-settings](https://github.com/aasmpro/django-zero-settings) too, that may help you in some cases.
